language: ruby
rvm:
  - 2.6.3

addons:
apt:
  packages:
  - make
  - libcurl4-openssl-dev

script:
  - make

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
