version: '3'
services:
  tum_projects:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - .:/srv/jekyll
    environment:
      JEKYLL_ENV: production
    ports:
      - '4000:4000'
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0"
